#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x redshift > /dev/null || redshift -c ~/.config/redshift/redshift.conf &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config focused_border_color "#d4be98"
bspc config border_width         2
bspc config window_gap           0
bspc config top_padding          0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

nitrogen --restore

killall q polybar
polybar main 
